spring:
  application:
    name: leave-service
  datasource:
    url: jdbc:postgresql://localhost:5433/leavedb
    username: leaveuser
    password: leavepassword
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  port: 8081

employee-service:
  url: http://localhost:8080

logging:
  level:
    com.hrapp: DEBUG
    org.hibernate.SQL: DEBUG